######################################################################################
#############   Aries ACA-Py ACC-Py Jupyter Playground Configuration   ###############
######################################################################################
############ This removes ngrok services
############ And uses a Dockerfile.agent.prod
############ This changes the startup script used see startup-prod.sh
############ You must define ACAPY_ENDPOINT in the .env file
############ This should be http://<somepublicip>:<exposed http port>
############ Where exposed http port is the HTTP PORT mapped to the machine
############ E.g. 4020:3020 would mean port is 4020
############ This port must be publically accessible for HTTP requests
############ You could of course turn this into a domain name instead
######################################################################################
version: "3"
services:
  mediator-wallet-db:
    image: postgres:11
    container_name: mediator-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - playground/mediator/.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mediator-domain
    tty: true
  mediator-agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.agent.prod
    env_file:
      - playground/mediator/.env
    ports:
      - 6666:3020
      - 3021:3021
    depends_on:
      - mediator-wallet-db
    networks:
      - mediator-domain
  mediator-business-logic:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.controller
    env_file:
      - playground/mediator/.env
    depends_on:
      - mediator-agent
    networks:
      - mediator-domain
    volumes:
      - ./playground/mediator/notebooks:/workspace
      - ./recipes:/workspace/recipes
      - ./libs:/workspace/libs
    ports:
      - "8888:8888"
      - 3010:3010
#    #### ACTOR TEMPLATE SERVICES - Uncomment and edit as appropriate ######
#      actor-wallet-db:
#        image: postgres:11
#        container_name: actor-wallet-db
#        command: postgres -c listen_addresses='*'
#        # env file defines
#        env_file:
#          - playground/actor/.env
#        volumes:
#          - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
#        networks:
#          - actor-domain
#        tty: true
#      actor-agent:
#        build:
#          context: .
#          dockerfile: dockerfiles/Dockerfile.agent
#        env_file:
#          - playground/actor/.env
#        ports:
#          # HTTP_PORT
#          - <UNIQUE_PORT>:3020
#          # ADMIN_PORT
#          - <UNIQUE_PORT>:3021
#        depends_on:
#          - actor-wallet-db
#        networks:
#          - actor-domain
#      actor-business-logic:
#        build:
#          context: .
#          dockerfile: dockerfiles/Dockerfile.controller
#        env_file:
#          - playground/actor/.env
#        depends_on:
#          - actor-agent
#        networks:
#          - actor-domain
#        volumes:
#          - ./playground/actor/notebooks:/workspace
#          - ./recipes:/workspace/recipes
#        ports:
#          - 8890:8888
#          # WEBHOOK_PORT
#          - <UNIQUE_PORT>:3010
##### UNCOMMENT FOR A TAILS SERVER ######
# Note - for revocation to work you will have to make additional changes to the env files
#  tails-server:
#    env_file:
#      - playground/alice/.env
#    build:
#      context: https://github.com/bcgov/indy-tails-server.git
#      dockerfile: docker/Dockerfile.tails-server
#    ports:
#      - 6543:6543
#    networks:
#      - demo-participant-domain
#      - hlgf-domain
#    command: >
#      tails-server
#        --host 0.0.0.0
#        --port 6543
#        --storage-path /tmp/tails-files
#        --log-level INFO
networks:
  mediator-domain:
